version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment: 
      # or - MONGO_INITDB_ROOT_USERNAME=goals
      MONGO_INITDB_ROOT_USERNAME: goals
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    # adding environment variables file
    # env_file: 
    #   - ./env/mongo.env
    # docker networks
    # networks: 
    #   - goals-network
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args: 
    #     some-arg: 1
    ports: 
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
  # frontend:

volumes: 
  data:
  logs: