version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # container_name: mongodb
    # environment: 
      # or - MONGO_INITDB_ROOT_USERNAME=goals
      # MONGO_INITDB_ROOT_USERNAME: max
      # MONGO_INITDB_ROOT_PASSWORD: secret
    # adding environment variables file
    env_file: 
      - ./env/mongo.env
    # docker networks
    # networks: 
    #   - goals-network
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args: 
    #     some-arg: 1
    ports: 
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on: 
      - mongodb
  frontend:
    build: './frontend'
    ports: 
      - '3000:3000'
    volumes: 
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes: 
  data:
  logs:

    # force build images 
    # docker-compose up --build
    # just build images
    # docker-compose build
